/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  "iframe-page": () => import("@/views/_builtin/iframe-page/[url].vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  add: () => import("@/views/add/index.vue"),
  addpl: () => import("@/views/addpl/index.vue"),
  addtj: () => import("@/views/addtj/index.vue"),
  adduser: () => import("@/views/adduser/index.vue"),
  atesa: () => import("@/views/atesa/index.vue"),
  atest: () => import("@/views/atest/index.vue"),
  charge: () => import("@/views/charge/index.vue"),
  chati: () => import("@/views/chati/index.vue"),
  class: () => import("@/views/class/index.vue"),
  data: () => import("@/views/data/index.vue"),
  ddtj: () => import("@/views/ddtj/index.vue"),
  dengji: () => import("@/views/dengji/index.vue"),
  dingdan: () => import("@/views/dingdan/index.vue"),
  docking: () => import("@/views/docking/index.vue"),
  dockinglog: () => import("@/views/dockinglog/index.vue"),
  fenlei: () => import("@/views/fenlei/index.vue"),
  gglist: () => import("@/views/gglist/index.vue"),
  guanx: () => import("@/views/guanx/index.vue"),
  help: () => import("@/views/help/index.vue"),
  home: () => import("@/views/home/index.vue"),
  huoyuan: () => import("@/views/huoyuan/index.vue"),
  jgjk: () => import("@/views/jgjk/index.vue"),
  kcid: () => import("@/views/kcid/index.vue"),
  list: () => import("@/views/list/index.vue"),
  log: () => import("@/views/log/index.vue"),
  logout: () => import("@/views/logout/index.vue"),
  main: () => import("@/views/main/index.vue"),
  mijia: () => import("@/views/mijia/index.vue"),
  myprice: () => import("@/views/myprice/index.vue"),
  passwd: () => import("@/views/passwd/index.vue"),
  pay: () => import("@/views/pay/index.vue"),
  paylist: () => import("@/views/paylist/index.vue"),
  pchangelist: () => import("@/views/pchangelist/index.vue"),
  rd: () => import("@/views/rd/index.vue"),
  sjqy: () => import("@/views/sjqy/index.vue"),
  smgz: () => import("@/views/smgz/index.vue"),
  tjuser: () => import("@/views/tjuser/index.vue"),
  usergj: () => import("@/views/usergj/index.vue"),
  userinfo: () => import("@/views/userinfo/index.vue"),
  userlist: () => import("@/views/userlist/index.vue"),
  usernotice: () => import("@/views/usernotice/index.vue"),
  webmsg: () => import("@/views/webmsg/index.vue"),
  webset: () => import("@/views/webset/index.vue"),
  workorder: () => import("@/views/workorder/index.vue"),
  yjdj: () => import("@/views/yjdj/index.vue"),
  zzbz: () => import("@/views/zzbz/index.vue"),
};
