/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

export const generatedRoutes: GeneratedRoute[] = [
  {
    name: '403',
    path: '/403',
    component: 'layout.blank$view.403',
    meta: {
      title: '403',
      i18nKey: 'route.403',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '404',
    path: '/404',
    component: 'layout.blank$view.404',
    meta: {
      title: '404',
      i18nKey: 'route.404',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: '500',
    path: '/500',
    component: 'layout.blank$view.500',
    meta: {
      title: '500',
      i18nKey: 'route.500',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'add',
    path: '/add',
    component: 'layout.base$view.add',
    meta: {
      title: '马上学习',
      icon: 'ph:shopping-cart-simple',
      order: 3
    }
  },
  {
    name: 'addpl',
    path: '/addpl',
    component: 'layout.base$view.addpl',
    meta: {
      title: '批量学习',
      icon: 'ph:stack',
      order: 4
    }
  },
  {
    name: 'addtj',
    path: '/addtj',
    component: 'layout.base$view.addtj',
    meta: {
      title: '无查提交',
      icon: 'ph:upload-simple',
      order: 5
    }
  },
  {
    name: 'adduser',
    path: '/adduser',
    component: 'layout.base$view.adduser',
    meta: {
      title: '添加代理',
      hideInMenu: true
    }
  },
  {
    name: 'atesa',
    path: '/atesa',
    component: 'layout.base$view.atesa',
    meta: {
      title: '下架专区',
      icon: 'ph:arrow-down',
      order: 10
    }
  },
  {
    name: 'atest',
    path: '/atest',
    component: 'layout.base$view.atest',
    meta: {
      title: '最新上架',
      icon: 'ph:arrow-up',
      order: 9
    }
  },
  {
    name: 'charge',
    path: '/charge',
    component: 'layout.base$view.charge',
    meta: {
      title: '在线充值',
      icon: 'ph:wallet',
      order: 20
    }
  },
  {
    name: 'chati',
    path: '/chati',
    component: 'layout.base$view.chati',
    meta: {
      title: '题库查询',
      icon: 'ph:read-cv-logo',
      order: 22
    }
  },
  {
    name: 'class',
    path: '/class',
    component: 'layout.base$view.class',
    meta: {
      title: '网课设置',
      icon: 'ph:books',
      order: 7,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'data',
    path: '/data',
    component: 'layout.base$view.data',
    meta: {
      title: '今日数据',
      icon: 'ph:calendar-check',
      order: 39,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'ddtj',
    path: '/ddtj',
    component: 'layout.base$view.ddtj',
    meta: {
      title: '货源统计',
      icon: 'ph:chart-bar',
      order: 38,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'dengji',
    path: '/dengji',
    component: 'layout.base$view.dengji',
    meta: {
      title: '等级设置',
      icon: 'ph:stairs',
      order: 36,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'dingdan',
    path: '/dingdan',
    component: 'layout.base$view.dingdan',
    meta: {
      title: '可用项目',
      icon: 'ph:check-square',
      order: 13
    }
  },
  {
    name: 'docking',
    path: '/docking',
    component: 'layout.base$view.docking',
    meta: {
      title: '串货对接',
      icon: 'ph:plugs',
      order: 17
    }
  },
  {
    name: 'fenlei',
    path: '/fenlei',
    component: 'layout.base$view.fenlei',
    meta: {
      title: '分类设置',
      icon: 'ph:folders',
      order: 35,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'gglist',
    path: '/gglist',
    component: 'layout.base$view.gglist',
    meta: {
      title: '公告列表',
      icon: 'ph:megaphone',
      order: 34,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'guanx',
    path: '/guanx',
    component: 'layout.base$view.guanx',
    meta: {
      title: '充值卡密',
      icon: 'ph:ticket',
      order: 40,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'help',
    path: '/help',
    component: 'layout.base$view.help',
    meta: {
      title: '必看说明',
      icon: 'ph:question',
      order: 15
    }
  },
  {
    name: 'home',
    path: '/home',
    component: 'layout.base$view.home',
    meta: {
      title: 'home',
      i18nKey: 'route.home',
      icon: 'mdi:monitor-dashboard',
      order: 1
    }
  },
  {
    name: 'huoyuan',
    path: '/huoyuan',
    component: 'layout.base$view.huoyuan',
    meta: {
      title: '接口配置',
      icon: 'ph:cloud-arrow-up',
      order: 8,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'iframe-page',
    path: '/iframe-page/:url',
    component: 'layout.base$view.iframe-page',
    props: true,
    meta: {
      title: 'iframe-page',
      i18nKey: 'route.iframe-page',
      constant: true,
      hideInMenu: true,
      keepAlive: true
    }
  },
  {
    name: 'jgjk',
    path: '/jgjk',
    component: 'layout.base$view.jgjk',
    meta: {
      title: '价格监控管理',
      hideInMenu: true,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'kcid',
    path: '/kcid',
    component: 'layout.base$view.kcid',
    meta: {
      title: 'kcid对比',
      icon: 'ph:code',
      order: 12
    }
  },
  {
    name: 'list',
    path: '/list',
    component: 'layout.base$view.list',
    meta: {
      title: '订单汇总',
      icon: 'ph:list-checks',
      order: 4
    }
  },
  {
    name: 'log',
    path: '/log',
    component: 'layout.base$view.log',
    meta: {
      title: '操作日志',
      icon: 'ph:note',
      order: 14
    }
  },
  {
    name: 'login',
    path: '/login/:module(pwd-login|code-login|register|reset-pwd|bind-wechat)?',
    component: 'layout.blank$view.login',
    props: true,
    meta: {
      title: 'login',
      i18nKey: 'route.login',
      constant: true,
      hideInMenu: true
    }
  },
  {
    name: 'logout',
    path: '/logout',
    component: 'layout.base$view.logout',
    meta: {
      title: '退出登录',
      icon: 'ph:sign-out',
      order: 99
    }
  },
  {
    name: 'main',
    path: '/main',
    component: 'layout.base$view.main',
    meta: {
      title: '个人综合',
      icon: 'ph:squares-four',
      order: 1
    }
  },
  {
    name: 'mijia',
    path: '/mijia',
    component: 'layout.base$view.mijia',
    meta: {
      title: '密价设置',
      icon: 'ph:tag',
      order: 37,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'myprice',
    path: '/myprice',
    component: 'layout.base$view.myprice',
    meta: {
      title: '学习价格',
      icon: 'ph:currency-circle-dollar',
      order: 16
    }
  },
  {
    name: 'passwd',
    path: '/passwd',
    component: 'layout.base$view.passwd',
    meta: {
      title: '修改密码',
      hideInMenu: true
    }
  },
  {
    name: 'pay',
    path: '/pay',
    component: 'layout.base$view.pay',
    meta: {
      title: '卡密充值',
      icon: 'ph:key',
      order: 19
    }
  },
  {
    name: 'paylist',
    path: '/paylist',
    component: 'layout.base$view.paylist',
    meta: {
      title: '支付订单',
      icon: 'ph:wallet',
      order: 9,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'pchangelist',
    path: '/pchangelist',
    component: 'layout.base$view.pchangelist',
    meta: {
      title: '价格变动',
      icon: 'ph:trend-up',
      order: 18
    }
  },
  {
    name: 'rd',
    path: '/rd',
    component: 'layout.base$view.rd',
    meta: {
      title: '热度排行',
      icon: 'ph:fire',
      order: 11
    }
  },
  {
    name: 'sjqy',
    path: '/sjqy',
    component: 'layout.base$view.sjqy',
    meta: {
      title: '上级迁移',
      hideInMenu: true
    }
  },
  {
    name: 'smgz',
    path: '/smgz',
    component: 'layout.base$view.smgz',
    meta: {
      title: '通知频道',
      hideInMenu: true
    }
  },
  {
    name: 'tjuser',
    path: '/tjuser',
    component: 'layout.base$view.tjuser',
    meta: {
      title: '强国录入账号',
      hideInMenu: true
    }
  },
  {
    name: 'usergj',
    path: '/usergj',
    component: 'layout.base$view.usergj',
    meta: {
      title: '修改费率',
      hideInMenu: true
    }
  },
  {
    name: 'userinfo',
    path: '/userinfo',
    component: 'layout.base$view.userinfo',
    meta: {
      title: '我的资料',
      icon: 'ph:user-circle',
      order: 5
    }
  },
  {
    name: 'userlist',
    path: '/userlist',
    component: 'layout.base$view.userlist',
    meta: {
      title: '代理管理',
      icon: 'ph:users-three',
      order: 6
    }
  },
  {
    name: 'usernotice',
    path: '/usernotice',
    component: 'layout.base$view.usernotice',
    meta: {
      title: '设置公告',
      hideInMenu: true
    }
  },
  {
    name: 'webmsg',
    path: '/webmsg',
    component: 'layout.base$view.webmsg',
    meta: {
      title: '系统信息',
      icon: 'ph:info',
      order: 32,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'webset',
    path: '/webset',
    component: 'layout.base$view.webset',
    meta: {
      title: '系统设置',
      icon: 'ph:gear-six',
      order: 10,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'workorder',
    path: '/workorder',
    component: 'layout.base$view.workorder',
    meta: {
      title: '问题反馈',
      icon: 'ph:headset',
      order: 21
    }
  },
  {
    name: 'yjdj',
    path: '/yjdj',
    component: 'layout.base$view.yjdj',
    meta: {
      title: '一键对接',
      icon: 'ph:link',
      order: 42,
      roles: ['R_SUPER']
    }
  },
  {
    name: 'zzbz',
    path: '/zzbz',
    component: 'layout.base$view.zzbz',
    meta: {
      title: '站长帮助',
      icon: 'ph:lifebuoy',
      order: 33,
      roles: ['R_SUPER']
    }
  }
];
